// Assuming the path to Msdk component is correct, adjust as necessary
import Head from "next/head";
import styles from "../../../styles/Home.module.css";
import { Msdk } from "../../../components/msdk";

const Home: React.FC = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <h2>@matterport/sdk</h2>
        <Msdk /> {/* Include the Matterport SDK component here */}
      </main>
      <footer className={styles.footer}>
        <a href="https://next.new" target="_blank" rel="noopener noreferrer">
          Created with&nbsp;<b>next.new</b>&nbsp;⚡️
        </a>
      </footer>
    </div>
  );
};

export default Home;
